/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kuis2;

/**
 *
 * @author NIA
 */
public class kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form kuis2
     */
    public kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        br1 = new javax.swing.JTextField();
        br2 = new javax.swing.JTextField();
        br3 = new javax.swing.JTextField();
        br4 = new javax.swing.JTextField();
        dis = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(213, 11, 60, 14);

        jLabel2.setText("Harga Barang 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(128, 39, 75, 14);

        jLabel3.setText("Harga Barang 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(128, 70, 75, 14);

        jLabel4.setText("Harga Barang 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(128, 101, 75, 14);

        jLabel5.setText("Harga Barang 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(128, 137, 75, 14);

        jLabel6.setText("Diskon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(128, 172, 31, 14);

        br1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                br1ActionPerformed(evt);
            }
        });
        getContentPane().add(br1);
        br1.setBounds(236, 36, 171, 20);
        getContentPane().add(br2);
        br2.setBounds(236, 67, 171, 20);

        br3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                br3ActionPerformed(evt);
            }
        });
        getContentPane().add(br3);
        br3.setBounds(236, 98, 171, 20);

        br4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                br4ActionPerformed(evt);
            }
        });
        getContentPane().add(br4);
        br4.setBounds(236, 134, 171, 20);
        getContentPane().add(dis);
        dis.setBounds(236, 172, 171, 20);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(138, 225, 65, 23);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(236, 225, 63, 23);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(322, 225, 63, 23);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(125, 266, 282, 153);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void br1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_br1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_br1ActionPerformed

    private void br3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_br3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_br3ActionPerformed

    private void br4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_br4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_br4ActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        int HargaBarang1 = Integer.parseInt(br1.getText());
        int HargaBarang2 = Integer.parseInt(br2.getText());
        int HargaBarang3 = Integer.parseInt(br3.getText());
        int HargaBarang4 = Integer.parseInt(br4.getText());
        int Diskon = Integer.parseInt(dis.getText());
        String Keterangan = "";
                
        if ( Diskon  == 50){
            int total = (HargaBarang1+HargaBarang2+HargaBarang3+HargaBarang4);
            int hasil = total * Diskon / 100;
            Keterangan = "\nDiskon anda   = "+Diskon+"\n"+"Total Harga    = "+total+"\n"+"Total Bayar = "+hasil;     
        }
        if ( Diskon  == 0){
            int total = (HargaBarang1+HargaBarang2+HargaBarang3+HargaBarang4);
            int hasil = total ;
            Keterangan = "\nDiskon anda   = "+Diskon+"\n"+"Total Harga    = "+total+"\n"+"Total Bayar = "+hasil;     
        }
        if ( Diskon  == 100){
            int total = (HargaBarang1+HargaBarang2+HargaBarang3+HargaBarang4);
            int hasil = total * 0;
            Keterangan = "\nDiskon anda   = "+Diskon+"\n"+"Total Harga    = "+total+"\n"+"Total Bayar = "+hasil;     
        }
       if ( Diskon  == 75){
            int total = (HargaBarang1+HargaBarang2+HargaBarang3+HargaBarang4);
            int hasil = total * Diskon / 100;
            Keterangan = "\nDiskon anda   = "+Diskon+"\n"+"Total Harga    = "+total+"\n"+"Total Bayar = "+hasil;     
        }
       else {
           Keterangan = " ";
       }
       hasil.setText("Harga Barang 1 : "+HargaBarang1+
                    "\n"+"Harga Barang 2 : "+HargaBarang2+
                    "\n"+"Harga Barang 3 : "+HargaBarang3+
                    "\n"+"Harga Barang 4 : "+HargaBarang4 + Keterangan);
                   
    }//GEN-LAST:event_prosesActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        hasil.setText("");
        br1.setText("");
        br2.setText("");
        br3.setText("");
        br4.setText("");
        dis.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField br1;
    private javax.swing.JTextField br2;
    private javax.swing.JTextField br3;
    private javax.swing.JTextField br4;
    private javax.swing.JTextField dis;
    private javax.swing.JButton hapus;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
