/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kuis1;

/**
 *
 * @author NIA
 */
public class kuis1 extends javax.swing.JFrame {

    /**
     * Creates new form kuis1
     */
    public kuis1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        ab = new javax.swing.JTextField();
        mp = new javax.swing.JTextField();
        ni = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 0));
        getContentPane().setLayout(null);

        jLabel1.setText("penilaian siswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(179, 11, 71, 14);

        jLabel2.setText("nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(118, 46, 26, 14);

        jLabel3.setText("absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(118, 84, 29, 14);

        jLabel4.setText("matpel");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(118, 115, 32, 14);

        jLabel5.setText("nilai");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(118, 146, 18, 14);

        nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmActionPerformed(evt);
            }
        });
        getContentPane().add(nm);
        nm.setBounds(202, 43, 75, 20);
        getContentPane().add(ab);
        ab.setBounds(202, 81, 75, 20);

        mp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpActionPerformed(evt);
            }
        });
        getContentPane().add(mp);
        mp.setBounds(202, 112, 75, 20);

        ni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niActionPerformed(evt);
            }
        });
        getContentPane().add(ni);
        ni.setBounds(202, 143, 75, 20);

        proses.setText("proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(169, 181, 65, 23);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(118, 222, 166, 96);

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 390, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmActionPerformed

    private void mpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpActionPerformed

    private void niActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        String nama = nm.getText();
        String absen = ab.getText();
        String matpel = mp.getText();
        int nilai = Integer.parseInt(ni.getText().toString());
        
        if ( nilai < 75){
            hasil.setText("Nama           : "+nama+
                    "\n"+"Absen          : "+absen+
                    "\n"+"Matpel            : "+matpel+
                    "\n"+"Nilai              : "+nilai+
                    "\n"+"Keterangan : Tidak lulus ");
        }
        if( nilai >=75 && nilai <100){
            hasil.setText("Nama           : "+nama+
                    "\n"+"Absen          : "+absen+
                    "\n"+"Matpel            : "+matpel+
                    "\n"+"Nilai              : "+nilai+
                    "\n"+"Keterangan : Lulus ");
        }
        if (nilai ==100){
            hasil.setText("Nama           : "+nama+
                    "\n"+"Absen          : "+absen+
                    "\n"+"Matpel            : "+matpel+
                    "\n"+"Nilai              : "+nilai+
                    "\n"+"Keterangan : Sempurna ");
        }
        if (nilai  >100){
            hasil.setText("Nama           : "+nama+
                    "\n"+"Absen           : "+absen+
                    "\n"+"Matpel          : "+matpel+
                    "\n"+"Nilai              : "+nilai+
                    "\n"+"Keterangan : Amazing ");
        }
    }//GEN-LAST:event_prosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ab;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mp;
    private javax.swing.JTextField ni;
    private javax.swing.JTextField nm;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
